version: '3.8'

services:
  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  
  postgres:
    image: postgres:15.6
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: caching_learn
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  api:
    build: .
    command: "bash -c 'sleep 15 && export FLASK_APP=src/app.py && flask db upgrade && flask run --host=0.0.0.0 --port=8080 --debug'"
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app:rw